update lab

diff --git a/welcome/jenkins/labs/e2e/jenkinsfile b/welcome/jenkins/labs/e2e/jenkinsfile
--- a/welcome/jenkins/labs/e2e/jenkinsfile
+++ b/welcome/jenkins/labs/e2e/jenkinsfile
@@ -1,24 +1,22 @@
 pipeline {
-    agent {label 'docker'}
+    agent { label 'linux || docker' }
 
-    // Define environment variables
     environment {
-        PYTHON_VERSIONS =  "3.8,3.9"
-        DOCKERHUB_CREDENTIALS =  "AsusHub"
-        REPO_NAME = "omerasus3"
-        APP_PATH = 'welcome/jenkins/labs/e2e/app'
-
+        PYTHON_VERSIONS = '3.8,3.9'
+        DOCKERHUB_CREDENTIALS = 'dockerhub-mogli-creds'
+        REPO_NAME = 'madaralmog'
+        APP_PATH = 'welcome/jenkins/pipelines-demos/ex4/app'
     }
 
     stages {
-        stage('Clone'){
-            steps{
-                git branch: 'jenkins-workshop', url: 'https://github.com/AsuSociety/devopshift-welcome.git'
+
+        stage('Clone Python Project') {
+            steps {
+                git branch: 'jenkins-workshop', url: 'https://github.com/almog2290/devopshift-welcome.git'
             }
         }
 
-
-        stage('Install Dependencies') {
+        stage('Install Dependencies && Run Test') {
             matrix {
                 axes {
                     axis {
@@ -27,7 +25,7 @@ pipeline {
                     }
                 }
                 stages {
-                    stage('Install') {
+                    stage('Install Dependencies') {
                         agent {
                             docker {
                                 image "python:${PYTHON_VER}" // Python version from the matrix
@@ -44,33 +42,21 @@ pipeline {
                             '''
                         }
                     }
-                }
-            }
-        }
 
-        stage('Test Application') {
-            matrix {
-                axes {
-                    axis {
-                        name 'PYTHON_VER'
-                        values 3.8 , 3.9
-                    }
-                }
-                stages {
                     stage('Run Test') {
                         agent {
                             docker {
-                                image "python:${PYTHON_VER}" // Python version from the matrix
-                                reuseNode true // TIP: Reuse the workspace for Docker containers
+                                image "python:${PYTHON_VER}" 
+                                reuseNode true // Reuse the workspace for Docker containers
                             }
                         }
                         steps {
                             dir(env.APP_PATH){
                                 sh '''
-                                export HOME=${WORKSPACE}
-                                set -e 
-                                python app.py
-                                '''      // TIP: Runs the Python script here and validate its output (expecting exit code 0 )   
+                                    export HOME=${WORKSPACE}
+                                    set -e  # Exit immediately if a command exits with a non-zero status
+                                    python app.py
+                                '''
                             }
                         }
                     }
@@ -78,12 +64,11 @@ pipeline {
             }
         }
 
-
-        stage('Build Docker Images') {
+        stage('Build & Push Docker Images') {
             matrix {
                 axes {
                     axis {
-                        name 'PYTHON_VER'
+                        name 'PYTHON_VER' 
                         values 3.8 , 3.9
                     }
                 }
@@ -94,34 +79,31 @@ pipeline {
                                 script {
                                     def IMAGE_NAME = "${REPO_NAME}/faker:${PYTHON_VER}-slim-1.0"
                                     echo "Building Docker image ${IMAGE_NAME}..."
-                                    docker.build(IMAGE_NAME)                                
+                                    docker.build(IMAGE_NAME)
                                 }
                             }
                         }
                     }
-                }
-            }
-        }
 
-        stage('Push to DockerHub') {
-            matrix {
-                axes {
-                    axis {
-                        name 'PYTHON_VER'
-                        values 3.8, 3.9
-                    }
-                }
-                stages {
                     stage('Push Image') {
-                        steps {
-                                script {
-                                    def IMAGE_NAME = "${env.REPO_NAME}/faker:${PYTHON_VER}-slim-1.0"
-                                    echo "Pushing Docker image ${IMAGE_NAME}..."
-                                    docker.withRegistry('https://index.docker.io/v1/', env.DOCKERHUB_CREDENTIALS) {
-                                        def appImage = docker.image(IMAGE_NAME)
-                                        appImage.push()
-                                    }
+                        steps{
+                            script {
+                                def IMAGE_NAME = "${REPO_NAME}/faker:${PYTHON_VER}-slim-1.0"
+                                echo "Pushing Docker image to DockerHub..."
+                                docker.withRegistry('https://index.docker.io/v1/', env.DOCKERHUB_CREDENTIALS) {
+                                    def appImage = docker.image(IMAGE_NAME)
+                                    appImage.push()
                                 }
+                            }
+                        }
+                    }
+
+                    stage('Clean Up') {
+                        steps {
+                            script{
+                                def IMAGE_NAME = "${REPO_NAME}/faker:${PYTHON_VER}-slim-1.0"
+                                sh "docker rmi ${IMAGE_NAME}"
+                            }
                         }
                     }
                 }
